name: notepadqq 
version: '1.4.8+git'
summary: A Notepad++-like editor for Linux.
description: |
  It helps developers by providing all you can expect from a general purpose text editor, such as syntax highlighting for more than 100 different languages, code folding, color schemes, file monitoring, multiple selection and much more.
  You can search text using the power of regular expressions. You can organize documents side by side. You can use real-time highlighting to find near identifiers in no time.
grade: stable
confinement: classic
icon: support_files/icons/hicolor/scalable/apps/notepadqq.svg


apps:
  notepadqq: 
    command: bash $SNAP/usr/bin/notepadqq-launch.sh $SNAP/usr/local/lib/notepadqq/notepadqq-bin
    desktop: usr/local/share/applications/notepadqq.desktop
#   plugs:  # Plugs are not needed for classic confinement
#     - browser-support
#     - desktop
#     - desktop-legacy
#     - gsettings
#     - home
#     - media-hub
#     - network-bind
#     - network-manager
#     - opengl
#     - optical-drive
#     - removable-media
#     - unity7
#     - x11

parts:

  qt-get:
    plugin: nil
    override-build: |
      echo "deb http://ppa.launchpad.net/beineri/opt-qt592-xenial/ubuntu xenial main" >> /etc/apt/sources.list
      echo "deb-src http://ppa.launchpad.net/beineri/opt-qt592-xenial/ubuntu xenial main" >> /etc/apt/sources.list
      echo "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu xenial main" >> /etc/apt/sources.list
      echo "deb-src http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu xenial main" >> /etc/apt/sources.list
      #add-apt-repository -y ppa:beineri/opt-qt595-xenial
      #add-apt-repository -y ppa:ubuntu-toolchain-r/test
      apt-get update
      apt-get install -y --allow-unauthenticated qt59base qt59webengine qt59webchannel qt59websockets qt59svg qt59tools
      #apt-get install -y gcc-7 g++-7

  qt:
    after: [qt-get]
    source: /opt
    plugin: dump
    organize:
      'qt59' : opt/qt59
    stage:
      - opt/qt59

  nqq:
    build-packages:
      - build-essential
      - freeglut3-dev

    stage-packages:
      - gcc-7
      - g++-7
      - libstdc++6
      - libnss3
      - adwaita-icon-theme-full
      - bamfdaemon
      - coreutils
      - desktop-file-utils
      - gnome-menus
      - gtk2-engines-pixbuf
      - hicolor-icon-theme
      - libatk-adaptor
      - libcanberra-gtk-module
      - libgail-common
      - light-themes
      - man-db
      - mime-support
      - numix-gtk-theme
      - overlay-scrollbar-gtk2
      - packagekit-gtk3-module
      - unity-gtk-module-common
      - unity-schemas

    source: . 
    after: [qt]
    plugin: nil
    override-build: |
      sed -i '/.*QMAKE_RPATH=$/d' src/ui/ui.pro  # Hack for forcing the use of RPATH
      bash "$SNAPCRAFT_STAGE"/../.snap-scripts/build.sh

  fixicon:
    plugin: nil
    after: [nqq]
    override-build: |
      sed -i 's|Icon=notepadqq|Icon=/usr/local/share/icons/hicolor/scalable/apps/notepadqq\.svg|' $SNAPCRAFT_STAGE/usr/local/share/applications/notepadqq.desktop

  launch-scripts:
    source: .snap-scripts
    plugin: dump
    organize:
      'notepadqq-launch.sh' : usr/bin/notepadqq-launch.sh
    stage:
      - usr/bin/notepadqq-launch.sh
